### ISSUE TITLE
Add Patient Modal 

### ISSUE THREAD

**Issue by psakurai** [Nrlilah/hmsJAVA#13]
Nationality field should not allowed number.

**Comment by izzaharsyd** [comment]
Identification Card No. field should not allowed characters and must have 12 numbers.

**Comment by izzaharsyd** [comment]
Date of Birth field should not allowed date after current date.

**Comment by izzaharsyd** [comment]
Appointment Date field should enter date after current date.

**Comment by izzaharsyd** [comment]
Address (Postcode) field should not allowed characters.

**Comment by Nrlilah** [comment]
name field tak boleh tambah '

**Comment by psakurai** [comment]
Fixed and merged.
