### ISSUE TITLE
Assign Medication Modal

### ISSUE THREAD

**Issue by Twowisesana** [Nrlilah/hmsJAVA#14]
Patient prescription cannot add

Tak keluar dropdown account; 
tak boleh tekan account setting dan sign out

Dekat header title ‘Patient Medication 0’, instead of ‘Patient Medication’

**Comment by izzaharsyd** [comment]
Prescribe (only read field) by field - only doctor can prescribe

**Comment by izzaharsyd** [comment]
header and sidenav not working

**Comment by psakurai** [comment]
Fixed and merged.
